// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxO47_Bcu2cII35ICMD2HcGKIRbjf22kc',
    appId: '1:970074959382:web:51909fc74b5f3f1b638f37',
    messagingSenderId: '970074959382',
    projectId: 'max-buy',
    authDomain: 'max-buy.firebaseapp.com',
    storageBucket: 'max-buy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpe_dZ5B-Ec32s7d2y4YdJR6teySMqBU',
    appId: '1:970074959382:android:cb5298b03f441d8e638f37',
    messagingSenderId: '970074959382',
    projectId: 'max-buy',
    storageBucket: 'max-buy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLHrmbInWAU36NrgGeDVfqtKolCLkcuA',
    appId: '1:970074959382:ios:061bac880f8e9e69638f37',
    messagingSenderId: '970074959382',
    projectId: 'max-buy',
    storageBucket: 'max-buy.appspot.com',
    iosClientId: '970074959382-4po9hfcer5tihkitgh7n9j8g1gvr0bu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxbuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLHrmbInWAU36NrgGeDVfqtKolCLkcuA',
    appId: '1:970074959382:ios:061bac880f8e9e69638f37',
    messagingSenderId: '970074959382',
    projectId: 'max-buy',
    storageBucket: 'max-buy.appspot.com',
    iosClientId: '970074959382-4po9hfcer5tihkitgh7n9j8g1gvr0bu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxbuy',
  );
}
